class APIKeyException(Exception):
    ...

class APIKeyNotFoundException(APIKeyException):
    ...

class NoAPIKeyInQueryException(APIKeyException):
    ...

class BadAPIKeyException(APIKeyException):
    ...
