class SiteCheckerException(Exception):
    ...

class CheckerAlreadyExistsException(SiteCheckerException):
    ...

class CheckerNotFoundException(SiteCheckerException):
    ...

class DeletingErrorException(SiteCheckerException):
    ...

